language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm
before_install:
- openssl aes-256-cbc -K $encrypted_ec75b5db0746_key -iv $encrypted_ec75b5db0746_iv
  -in api-key.php.enc -out api-key.php -d
before_script:
- curl -s http://getcomposer.org/installer | php
- php composer.phar self-update
- php composer.phar install --dev --no-interaction --prefer-source
script:
- mkdir -p build/logs
- mkdir -p build/cov
- php vendor/bin/phpcs --config-set show_warnings 0
- php vendor/bin/phpcs ./includes --standard=PSR1 --encoding=utf-8
- php vendor/bin/phpcs ./includes --standard=PSR2 --encoding=utf-8
- php vendor/bin/phpunit -c phpunit.xml.dist
after_script:
- php vendor/bin/coveralls
